    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install prerequisites for Docker
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create the keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository with trusted option
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 trusted=yes] https://download.docker.com/linux/ubuntu mantic stable"
        create: yes

    - name: Update apt package index after adding Docker repository
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
