    - name: Download Wazuh Agent package using wget
      become: true
      ansible.builtin.command:
        cmd: "wget --no-check-certificate https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.5-1_amd64.deb -O /tmp/wazuh-agent_4.7.5-1_amd64.deb"

    - name: Install Wazuh Agent package
      become: true
      ansible.builtin.apt:
        deb: /tmp/wazuh-agent_4.7.5-1_amd64.deb

    - name: Upload ossec.conf
      become: true
      ansible.builtin.copy:
        src: ./ossec.conf
        dest: /var/ossec/etc/ossec.conf

    - name: Reload systemd manager configuration
      become: true
      ansible.builtin.command:
        cmd: systemctl daemon-reload
      changed_when: false

    - name: Enable wazuh-agent service
      become: true
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: true

    - name: Start wazuh-agent service
      become: true
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started

    - name: Ensure the monitoring directory exists
      ansible.builtin.file:
        path: "/home/ansible/monitoring"
        state: directory
        mode: '0755'

    - name: Download the docker-compose.yml file
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/DaandeJong100/Homelab/refs/heads/main/docker/monitoring/docker-compose.yml"
        dest: "/home/ansible/monitoring/docker-compose.yml"
        mode: '0644'

    - name: Start the Docker Compose stack
      ansible.builtin.shell: |
        sudo docker compose up -d
      args:
        chdir: "/home/ansible/monitoring"
